N高模写ご指摘いただいた箇所の修正
mayu222/mayuarakawa pull request #4
Opened 2020-06-24 11:26 UTC by mayu222

- 均等割付text-align-last追加
- metaタグの追加
- リンク文字サイズ変更
- ページ上部のレイアウト微調整
- 画像縦横比維持のためのスタイルを追加

2020-06-27 00:56 UTC, kouyanh commented on html-nkou/css/style.css
> +.fit_1 {
命名に1とか2とかは本来あんまりよくない。今回はそのままで良いですが、特に注意するようにしておいてください。
https://dic.nicovideo.jp/a/%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC

2020-06-27 01:08 UTC, mayu222 commented on html-nkou/css/style.css
> +.fit_1 {
ありがとうございます！今後注意していきます。

2020-07-11 10:25 UTC, n06Ar requested changes
ページ全体的にですが、フォントの影響のためか比較的にフォントサイズが小さくなっているため調整をお願いします
また、開発環境的に確認が難しいかと思いますので可能ならで良いのですが、Safariでヘッダーのレイアウト崩れが発生していたのでフォントサイズや余白を修正していただければ良いと思います

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +    <title>N高</title>
タイトルが元のページと比べると短いです
`N高について | N高等学校(通信制高校 広域・単位制)`

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/css/style.css
> +.flex a {
`.flex`がHTML中に見当たりませんでした
使用していないCSSは影響範囲を見極めながら極力削除するようにしてください

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                    <div class="sns">
SNSのアイコンが元のページと比較して下によっています
ここのdivは`display:inline-block`を使用しているので、`vertical-align`を使うか、`div.header_item`でflexboxを使うなどして位置を調節してください

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                <img src="css/images/about_img02_01_20170927.png" alt="life_cycle" class="fit_1">
ここの行以外のalt属性を含めてalt属性の内容が画像が表示されなかった代わりの説明としては不足している物があります

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                        <img src="css/images/text_basic_program01_white01.png" width="100" height="15" alt="basic_white">
上寄りに表示されているため`vertical-align`を使用して位置を調節してください

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                        <img src="css/images/text_basic_program01_white01.png" width="100" height="15" alt="basic_white">
171、192、209、227、237、244、263、297行目も同様です

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                    <img src="css/images/mainlogo.png" width="220" height="50" alt="N高等学校">
元のページではリンクになっていますが、aタグがないためリンクになっていませんでした
aタグを追加してください

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/css/style.css
> +    min-width: 1050px;
widthにpxでの固定値の1050pxが設定されているため、min-widthの1050pxは機能していないのでこの場合不要です
`max-width`や`min-width`は、主に`width`が%やhw、hvなどの比率系の単位が指定されている時にpxで最低最高の横幅をつける時に使用します

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                    <img src="css/images/mainlogo.png" width="220" height="50" alt="N高等学校">
imgタグのwidth属性やheight属性を指定する場合は、CSSで`width: auto`か `height: auto;`を指定しなければ画像の縦横比率が崩れるので気をつけてください

元のサイトでは、ここは`width: 211px; height: 45px;`を設定されていたので確認してみてください

2020-07-11 10:25 UTC, n06Ar commented on html-nkou/index.html
> +                        <p>受付時間：平日10:00〜19:00</p>
この行のpタグの`margin-bottom`で下部にある「N高について」などの要素と余白をつけていますが、親の親のタグの`div.header_item`で余白の設定（`margin`か`padding`）をすると良いです

2020-07-11 10:47 UTC, n06Ar reviewed
追記で必須でない修正のコメントをしました
ご確認いただければと思います

2020-07-11 10:47 UTC, n06Ar commented on html-nkou/css/style.css
> +    background-image: url(../css/images/icon_arrow01_right_white01.png);
`./images/icon_arrow01_right_white01.png`でも良いと思います
この参照の仕方では、` html-nkou/css`から一度親のディレクトリ` html-nkou`に移動してから` html-nkou/css/images`で画像を参照するようになっています

2020-07-11 10:47 UTC, n06Ar commented on html-nkou/css/style.css
> +.fixed {
少しレベルが高い指摘なため可能であれば、今後意識していただければと思います
fixedのクラス名からスタイルが適用されるタグ要素が想像しづらいため、ある程度クラス名から意味を推測できるような命名をしていただければと思います

2020-07-11 10:47 UTC, n06Ar commented on html-nkou/index.html
> +                    <ul class="head_link_list">
これはin my opinionです
このulタグの内容はナビゲーションなためnavタグで囲っても良いと思います
類似したサイトのナビゲーションのコンテンツも同様です

2020-07-11 10:47 UTC, n06Ar commented on html-nkou/index.html
> +            <a href="#">N高等学校 | 通信制高校(広域)・単位制</a> &gt; N高について
これはin my opinionです
ここは`ul`タグと`li`タグを組み合わせてパンくずリストを作っても良いと思います
この場合は`>`などのデザインは、CSSに記述するとHTMLは文章でCSSは見た目と役割の住み分けができます

2020-07-12 13:38 UTC, n06Ar requested changes
追加で修正をお願いしたい点です
ご確認をお願いします

2020-07-12 13:38 UTC, n06Ar commented on html-nkou/index.html
> +                        <img src="css/images/text_read_more01_black01.png" width="70" height="13" alt="read_more">
他のRead Moreの画像に対しても同様に対応をお願いします
この画像に`vertical-align:top`をつけて位置調整をお願いします
下によりに表示されています

2020-07-12 14:20 UTC, n06Ar reviewed
修正が必須ではないものとin my opinion（このコメントはimo:を先頭においてコメントしています）の指摘を追記しました

2020-07-12 14:20 UTC, n06Ar commented on html-nkou/css/style.css
> +.head_link_list li:nth-child(n+6) {
imo:
`li:last-child`を使うと今後を考えると楽になります
数字で指定しているため、項目を追加するごとに修正が発生して手間なため最後の小要素を指定する`:last-child`擬似クラスを使用します
https://developer.mozilla.org/ja/docs/Web/CSS/:last-child

2020-07-12 14:20 UTC, n06Ar commented on html-nkou/index.html
> +                    <nav>
Safariでのレイアウト崩れのため修正は必須ではないです
このnavタグに[flex-basis](https://developer.mozilla.org/ja/docs/Web/CSS/flex-basis)で横幅を決めるとレイアウト崩れを防げます

2020-07-12 14:20 UTC, n06Ar commented on html-nkou/index.html
> +                <ul class="sns">
Safariでのレイアウト崩れのため修正は必須ではないです
このulタグにflex-basisで横幅を決めるとレイアウト崩れを防げます

2020-07-12 14:36 UTC, n06Ar commented on html-nkou/index.html
> +                        <p>受付時間：平日10:00〜19:00</p>
指摘内容に誤りがあったので修正します
申し訳ありません
> この行のpタグのmargin-bottomで下部にある「N高について」などの要素と余白をつけていますが、親の親のタグのdiv.header_itemで余白の設定（marginかpadding）をすると良いです

「親の親のタグのdiv.header_item」 とありますが、31行目の`<div class="header_logo navi_container">`でmargin-bottomを設定するようにしてください

この指摘の意図としては、この行のpタグで作った`margin-bottom`の余白は、本来は31行目`<div class="header_logo navi_container">`と49行目`<div class="school_menu navi_container">`間の余白の問題のため、`<div class="header_logo navi_container">`の小要素のpタグで余白を取るのは避けたい意図です

2020-07-14 22:33 UTC, n06Ar approved these changes
LGTM!

2020-07-14 22:48 UTC, merged